model:
  think:
    name: AuctionNetThinkModel
    verbose: 0
    llm_backend:
      # type: transformers
      # model_path: /DATA/xuehy/agent/models/Qwen/Qwen2.5-3B-Instruct
      # temperature: 0.0
      # max_tokens: 1024
      # stop: []
      # device: cuda:0

      type: vllm
      model_path: /DATA/xuehy/agent/models/Qwen/Qwen2.5-3B-Instruct
      temperature: 0.0
      max_tokens: 1024
      stop: []
      tensor_parallel_size: 1
      gpu_memory_utilization: 0.9

      # type: openai
      # model_path: gpt-4o
      # temperature: 0.0
      # max_tokens: 1024
      # stop: []
      # base_url: https://api.openai.com/v1
      # api_key: YOUR_API_KEY
      # timeout: 120.0
  act:
    name: ActModelV2 # 旧版: ActModel 新版 ActModel[V1|V2|DT]
    path: /DATA/xuehy/agent/models/Qwen/Qwen2.5-0.5B-Instruct
    backend: transformers
    device: cuda:1

task:
  state_dim: 16
  action_dim: 1
  window_size: 10

train:
  think:
    data_path: /DATA/xuehy/ad/AGB/traj5_2.pkl
    num_epochs: 6
    per_device_train_batch_size: 4
    gradient_accumulation_steps: 4
    learning_rate: 1.0e-4
    warmup_ratio: 0.1
    max_seq_length: 2048
    logging_steps: 10
    save_steps: 100
    save_total_limit: null
    finetune_mode: full  # qlora | full
    lora_r: 16
    lora_alpha: 32
    lora_dropout: 0.05
  act:
    data_path: /storage/xuehy/auctionnet/trajectory/sparse_pacer/part_{0..19}_thought.pkl
    optimizer: AdamW
    learning_rate: 0.00001
    batch_size: 32
    grad_accum_steps: 1
    n_step: 60000
    eval_interval: null
    log_interval: 100
    save_interval: 2000
    filter_thoughts:
      mode: nonconflict  # match | nonconflict | any
      default_action: 1.0
    loss_weights:
      action: 1.0
      rtg: 1.0
      state: 1.0
    amp: bfloat16

infer:
  strategy:
    name: AuctionNetBaseStrtegy
  valid:
    env:
      name: AuctionNetEnv
      data_path: /storage/xuehy/auctionnet/traffic/sparse/period-7.csv
      min_remaining_budget: 0.1
  explore:
    env:
      name: AuctionNetEnv
      data_path: /storage/xuehy/auctionnet/traffic/sparse/period-7.csv
      min_remaining_budget: 0.1
    override_temperature: 0.7
    override_top_p: 0.95
    n_sample: 4
  test:
    env:
      name: AuctionNetEnv
      data_path: /storage/xuehy/auctionnet/traffic/sparse/period-{8..13}.csv
      min_remaining_budget: 0.1
  think_batch_size: 144
  act_batch_size: 16

device: cuda
