model:
  think_model:
    name: AuctionNetThinkModel
    path: /DATA/xuehy/agent/models/Qwen/Qwen2.5-3B-Instruct
    backend: transformers
    temperature: 0.0
    max_tokens: 1024
    verbose: 0
  act_model:
    name: ActModel
    path: /DATA/xuehy/agent/models/Qwen/Qwen2.5-0.5B-Instruct
    backend: transformers
    normalize_dict_path: /DATA/xuehy/ad/AAB/aab/saved_model/DTtest_stable_20260119131013/normalize_dict.pkl
    temperature: 0.0
    max_tokens: 1024

strategy:
  name: AuctionNetBaseStrtegy
  state_dim: 16
  action_dim: 1
  window_size: 20

env:
  name: AuctionNetEnv
  data_path: /DATA/xuehy/ad/AAB/data/traffic/period-7.csv
  min_remaining_budget: 0.1

device: cuda
